export const AUDIO_CONFIG = {
  SAMPLE_RATE: 16000,
  ECHO_CANCELLATION: true,
  NOISE_SUPPRESSION: true,
  AUTO_GAIN_CONTROL: true,
};

export const RECOGNITION_CONFIG = {
  LANGUAGE: 'ja-JP',
  CONTINUOUS: true,
  INTERIM_RESULTS: true,
  MAX_ALTERNATIVES: 1,
};

export const SENTIMENT_CONFIG = {
  MIN_TEXT_LENGTH: 3,
  MAX_RESULTS: 100,
  CONFIDENCE_THRESHOLD: 0.1,
};

export const CHART_COLORS = {
  POSITIVE: '#10B981',
  NEGATIVE: '#EF4444',
  NEUTRAL: '#6B7280',
};

export const UI_CONSTANTS = {
  RECORDING_BUTTON_SIZE: 128,
  AUDIO_LEVEL_BARS: 20,
  CHART_HEIGHT: 256,
};